# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  main-db:
    container_name: go-postgres
    image: postgres:latest

    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  #### just in case
  # queues:
  #   image: rabbitmq:3-management-alpine
  #   container_name: go-queues
  #   ports:
  #     - 5672:5672
  #     - 15672:15672 # RabbitMQ GUI
  #   volumes:
  #     - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
  #     - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
  #   restart: always
  #   networks:
  #     - dev-network
  #   environment:

  # go:
  #   container_name: go
  #   # build the Dockerfile, alternatively use an image.
  #   build:
  #     context: .
  #   depends_on:
  #     - "main-db"

volumes:
  dbdata: # create the volume for persisting data.
